app = "botthew-office"
primary_region = "ord"

[build]
  image = "office-app"

[env]
  PORT = "3000"
  AUTH_PASSWORD = "${AUTH_PASSWORD}"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[statics]]
  guest_path = "/public"
  url_path = "/static"